# Generated by Django 5.0.7 on 2024-08-07 12:34

import videos.tasks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='genre',
            field=models.CharField(choices=[('animals', 'ANIMALS'), ('mountains', 'MOUNTAINS'), ('sea', 'SEA')], default='animals', max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=videos.tasks.video_upload_to),
        ),
    ]
